[2025-10-28T12:24:23.044-0400] {processor.py:157} INFO - Started process (PID=27529) to work on /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T12:24:23.045-0400] {processor.py:829} INFO - Processing file /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-28T12:24:23.045-0400] {logging_mixin.py:151} INFO - [2025-10-28T12:24:23.045-0400] {dagbag.py:539} INFO - Filling up the DagBag from /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T12:24:23.048-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/dataset.py:23 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:24:23.049-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/dataset.py:38 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:24:23.049-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/dataset.py:54 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:24:23.050-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/dataset.py:74 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:24:23.051-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/dag_run.py:26 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:24:23.260-0400] {processor.py:839} INFO - DAG(s) dict_keys(['example_local_kubernetes_executor']) retrieved from /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T12:24:23.267-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/taskinstance.py:27 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:24:23.294-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/serialized_objects.py:1527 DeprecationWarning: This module is deprecated. The `cncf.kubernetes` provider before version 7.4.0 uses this module - you should migrate to a newer version of `cncf.kubernetes` to get rid of this warning. If you import the module via `airflow.kubernetes` import, please use `cncf.kubernetes' provider 7.4.0+ and switch all your imports to use `apache.airflow.providers.cncf.kubernetes` to get rid of the warning.
[2025-10-28T12:24:23.308-0400] {logging_mixin.py:151} INFO - [2025-10-28T12:24:23.308-0400] {dag.py:2915} INFO - Sync 1 DAGs
[2025-10-28T12:24:23.311-0400] {logging_mixin.py:151} INFO - [2025-10-28T12:24:23.311-0400] {dag.py:3696} INFO - Setting next_dagrun for example_local_kubernetes_executor to None, run_after=None
[2025-10-28T12:24:23.316-0400] {processor.py:179} INFO - Processing /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.272 seconds
[2025-10-28T12:25:31.982-0400] {processor.py:157} INFO - Started process (PID=28254) to work on /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T12:25:31.984-0400] {processor.py:829} INFO - Processing file /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-28T12:25:31.985-0400] {logging_mixin.py:151} INFO - [2025-10-28T12:25:31.984-0400] {dagbag.py:539} INFO - Filling up the DagBag from /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T12:25:31.988-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/dataset.py:23 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:25:31.988-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/dataset.py:38 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:25:31.989-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/dataset.py:54 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:25:31.990-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/dataset.py:74 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:25:31.990-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/dag_run.py:26 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:25:32.251-0400] {processor.py:839} INFO - DAG(s) dict_keys(['example_local_kubernetes_executor']) retrieved from /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T12:25:32.258-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/taskinstance.py:27 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:25:32.285-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/serialized_objects.py:1527 DeprecationWarning: This module is deprecated. The `cncf.kubernetes` provider before version 7.4.0 uses this module - you should migrate to a newer version of `cncf.kubernetes` to get rid of this warning. If you import the module via `airflow.kubernetes` import, please use `cncf.kubernetes' provider 7.4.0+ and switch all your imports to use `apache.airflow.providers.cncf.kubernetes` to get rid of the warning.
[2025-10-28T12:25:32.301-0400] {logging_mixin.py:151} INFO - [2025-10-28T12:25:32.300-0400] {dag.py:2915} INFO - Sync 1 DAGs
[2025-10-28T12:25:32.303-0400] {logging_mixin.py:151} INFO - [2025-10-28T12:25:32.303-0400] {dag.py:3696} INFO - Setting next_dagrun for example_local_kubernetes_executor to None, run_after=None
[2025-10-28T12:25:32.308-0400] {processor.py:179} INFO - Processing /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.326 seconds
[2025-10-28T12:26:42.813-0400] {processor.py:157} INFO - Started process (PID=28931) to work on /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T12:26:42.815-0400] {processor.py:829} INFO - Processing file /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-28T12:26:42.815-0400] {logging_mixin.py:151} INFO - [2025-10-28T12:26:42.815-0400] {dagbag.py:539} INFO - Filling up the DagBag from /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T12:26:42.818-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/dataset.py:23 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:26:42.819-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/dataset.py:38 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:26:42.819-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/dataset.py:54 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:26:42.820-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/dataset.py:74 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:26:42.821-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/dag_run.py:26 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:26:43.029-0400] {processor.py:839} INFO - DAG(s) dict_keys(['example_local_kubernetes_executor']) retrieved from /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T12:26:43.036-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/taskinstance.py:27 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:26:43.062-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/serialized_objects.py:1527 DeprecationWarning: This module is deprecated. The `cncf.kubernetes` provider before version 7.4.0 uses this module - you should migrate to a newer version of `cncf.kubernetes` to get rid of this warning. If you import the module via `airflow.kubernetes` import, please use `cncf.kubernetes' provider 7.4.0+ and switch all your imports to use `apache.airflow.providers.cncf.kubernetes` to get rid of the warning.
[2025-10-28T12:26:43.076-0400] {logging_mixin.py:151} INFO - [2025-10-28T12:26:43.076-0400] {dag.py:2915} INFO - Sync 1 DAGs
[2025-10-28T12:26:43.079-0400] {logging_mixin.py:151} INFO - [2025-10-28T12:26:43.079-0400] {dag.py:3696} INFO - Setting next_dagrun for example_local_kubernetes_executor to None, run_after=None
[2025-10-28T12:26:43.084-0400] {processor.py:179} INFO - Processing /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.272 seconds
[2025-10-28T12:27:49.726-0400] {processor.py:157} INFO - Started process (PID=29596) to work on /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T12:27:49.728-0400] {processor.py:829} INFO - Processing file /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-28T12:27:49.729-0400] {logging_mixin.py:151} INFO - [2025-10-28T12:27:49.729-0400] {dagbag.py:539} INFO - Filling up the DagBag from /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T12:27:49.732-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/dataset.py:23 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:27:49.733-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/dataset.py:38 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:27:49.733-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/dataset.py:54 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:27:49.734-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/dataset.py:74 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:27:49.734-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/dag_run.py:26 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:27:49.963-0400] {processor.py:839} INFO - DAG(s) dict_keys(['example_local_kubernetes_executor']) retrieved from /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T12:27:49.970-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/taskinstance.py:27 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:27:49.996-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/serialized_objects.py:1527 DeprecationWarning: This module is deprecated. The `cncf.kubernetes` provider before version 7.4.0 uses this module - you should migrate to a newer version of `cncf.kubernetes` to get rid of this warning. If you import the module via `airflow.kubernetes` import, please use `cncf.kubernetes' provider 7.4.0+ and switch all your imports to use `apache.airflow.providers.cncf.kubernetes` to get rid of the warning.
[2025-10-28T12:27:50.011-0400] {logging_mixin.py:151} INFO - [2025-10-28T12:27:50.011-0400] {dag.py:2915} INFO - Sync 1 DAGs
[2025-10-28T12:27:50.014-0400] {logging_mixin.py:151} INFO - [2025-10-28T12:27:50.014-0400] {dag.py:3696} INFO - Setting next_dagrun for example_local_kubernetes_executor to None, run_after=None
[2025-10-28T12:27:50.020-0400] {processor.py:179} INFO - Processing /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.294 seconds
[2025-10-28T12:29:00.896-0400] {processor.py:157} INFO - Started process (PID=30248) to work on /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T12:29:00.897-0400] {processor.py:829} INFO - Processing file /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-28T12:29:00.898-0400] {logging_mixin.py:151} INFO - [2025-10-28T12:29:00.897-0400] {dagbag.py:539} INFO - Filling up the DagBag from /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T12:29:00.901-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/dataset.py:23 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:29:00.902-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/dataset.py:38 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:29:00.902-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/dataset.py:54 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:29:00.903-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/dataset.py:74 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:29:00.903-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/dag_run.py:26 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:29:01.121-0400] {processor.py:839} INFO - DAG(s) dict_keys(['example_local_kubernetes_executor']) retrieved from /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T12:29:01.129-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/taskinstance.py:27 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:29:01.158-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/serialized_objects.py:1527 DeprecationWarning: This module is deprecated. The `cncf.kubernetes` provider before version 7.4.0 uses this module - you should migrate to a newer version of `cncf.kubernetes` to get rid of this warning. If you import the module via `airflow.kubernetes` import, please use `cncf.kubernetes' provider 7.4.0+ and switch all your imports to use `apache.airflow.providers.cncf.kubernetes` to get rid of the warning.
[2025-10-28T12:29:01.174-0400] {logging_mixin.py:151} INFO - [2025-10-28T12:29:01.174-0400] {dag.py:2915} INFO - Sync 1 DAGs
[2025-10-28T12:29:01.177-0400] {logging_mixin.py:151} INFO - [2025-10-28T12:29:01.177-0400] {dag.py:3696} INFO - Setting next_dagrun for example_local_kubernetes_executor to None, run_after=None
[2025-10-28T12:29:01.183-0400] {processor.py:179} INFO - Processing /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.287 seconds
[2025-10-28T12:30:14.926-0400] {processor.py:157} INFO - Started process (PID=30948) to work on /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T12:30:14.928-0400] {processor.py:829} INFO - Processing file /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-28T12:30:14.928-0400] {logging_mixin.py:151} INFO - [2025-10-28T12:30:14.928-0400] {dagbag.py:539} INFO - Filling up the DagBag from /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T12:30:14.932-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/dataset.py:23 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:30:14.933-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/dataset.py:38 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:30:14.934-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/dataset.py:54 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:30:14.935-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/dataset.py:74 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:30:14.935-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/dag_run.py:26 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:30:15.176-0400] {processor.py:839} INFO - DAG(s) dict_keys(['example_local_kubernetes_executor']) retrieved from /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T12:30:15.184-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/taskinstance.py:27 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:30:15.214-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/serialized_objects.py:1527 DeprecationWarning: This module is deprecated. The `cncf.kubernetes` provider before version 7.4.0 uses this module - you should migrate to a newer version of `cncf.kubernetes` to get rid of this warning. If you import the module via `airflow.kubernetes` import, please use `cncf.kubernetes' provider 7.4.0+ and switch all your imports to use `apache.airflow.providers.cncf.kubernetes` to get rid of the warning.
[2025-10-28T12:30:15.231-0400] {logging_mixin.py:151} INFO - [2025-10-28T12:30:15.231-0400] {dag.py:2915} INFO - Sync 1 DAGs
[2025-10-28T12:30:15.234-0400] {logging_mixin.py:151} INFO - [2025-10-28T12:30:15.234-0400] {dag.py:3696} INFO - Setting next_dagrun for example_local_kubernetes_executor to None, run_after=None
[2025-10-28T12:30:15.243-0400] {processor.py:179} INFO - Processing /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.318 seconds
[2025-10-28T12:31:31.632-0400] {processor.py:157} INFO - Started process (PID=31661) to work on /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T12:31:31.634-0400] {processor.py:829} INFO - Processing file /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-28T12:31:31.635-0400] {logging_mixin.py:151} INFO - [2025-10-28T12:31:31.635-0400] {dagbag.py:539} INFO - Filling up the DagBag from /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T12:31:31.638-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/dataset.py:23 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:31:31.638-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/dataset.py:38 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:31:31.639-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/dataset.py:54 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:31:31.639-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/dataset.py:74 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:31:31.640-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/dag_run.py:26 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:31:31.872-0400] {processor.py:839} INFO - DAG(s) dict_keys(['example_local_kubernetes_executor']) retrieved from /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T12:31:31.879-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/taskinstance.py:27 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:31:31.906-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/serialized_objects.py:1527 DeprecationWarning: This module is deprecated. The `cncf.kubernetes` provider before version 7.4.0 uses this module - you should migrate to a newer version of `cncf.kubernetes` to get rid of this warning. If you import the module via `airflow.kubernetes` import, please use `cncf.kubernetes' provider 7.4.0+ and switch all your imports to use `apache.airflow.providers.cncf.kubernetes` to get rid of the warning.
[2025-10-28T12:31:31.921-0400] {logging_mixin.py:151} INFO - [2025-10-28T12:31:31.921-0400] {dag.py:2915} INFO - Sync 1 DAGs
[2025-10-28T12:31:31.923-0400] {logging_mixin.py:151} INFO - [2025-10-28T12:31:31.923-0400] {dag.py:3696} INFO - Setting next_dagrun for example_local_kubernetes_executor to None, run_after=None
[2025-10-28T12:31:31.928-0400] {processor.py:179} INFO - Processing /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.297 seconds
[2025-10-28T12:32:41.646-0400] {processor.py:157} INFO - Started process (PID=32297) to work on /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T12:32:41.648-0400] {processor.py:829} INFO - Processing file /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-28T12:32:41.648-0400] {logging_mixin.py:151} INFO - [2025-10-28T12:32:41.648-0400] {dagbag.py:539} INFO - Filling up the DagBag from /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T12:32:41.651-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/dataset.py:23 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:32:41.652-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/dataset.py:38 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:32:41.652-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/dataset.py:54 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:32:41.653-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/dataset.py:74 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:32:41.653-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/dag_run.py:26 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:32:41.873-0400] {processor.py:839} INFO - DAG(s) dict_keys(['example_local_kubernetes_executor']) retrieved from /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T12:32:41.881-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/taskinstance.py:27 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:32:41.907-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/serialized_objects.py:1527 DeprecationWarning: This module is deprecated. The `cncf.kubernetes` provider before version 7.4.0 uses this module - you should migrate to a newer version of `cncf.kubernetes` to get rid of this warning. If you import the module via `airflow.kubernetes` import, please use `cncf.kubernetes' provider 7.4.0+ and switch all your imports to use `apache.airflow.providers.cncf.kubernetes` to get rid of the warning.
[2025-10-28T12:32:41.923-0400] {logging_mixin.py:151} INFO - [2025-10-28T12:32:41.923-0400] {dag.py:2915} INFO - Sync 1 DAGs
[2025-10-28T12:32:41.925-0400] {logging_mixin.py:151} INFO - [2025-10-28T12:32:41.925-0400] {dag.py:3696} INFO - Setting next_dagrun for example_local_kubernetes_executor to None, run_after=None
[2025-10-28T12:32:41.930-0400] {processor.py:179} INFO - Processing /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.285 seconds
[2025-10-28T12:33:50.300-0400] {processor.py:157} INFO - Started process (PID=32942) to work on /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T12:33:50.302-0400] {processor.py:829} INFO - Processing file /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-28T12:33:50.302-0400] {logging_mixin.py:151} INFO - [2025-10-28T12:33:50.302-0400] {dagbag.py:539} INFO - Filling up the DagBag from /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T12:33:50.306-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/dataset.py:23 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:33:50.306-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/dataset.py:38 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:33:50.307-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/dataset.py:54 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:33:50.308-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/dataset.py:74 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:33:50.308-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/dag_run.py:26 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:33:50.657-0400] {processor.py:839} INFO - DAG(s) dict_keys(['example_local_kubernetes_executor']) retrieved from /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T12:33:50.668-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/taskinstance.py:27 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:33:50.704-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/serialized_objects.py:1527 DeprecationWarning: This module is deprecated. The `cncf.kubernetes` provider before version 7.4.0 uses this module - you should migrate to a newer version of `cncf.kubernetes` to get rid of this warning. If you import the module via `airflow.kubernetes` import, please use `cncf.kubernetes' provider 7.4.0+ and switch all your imports to use `apache.airflow.providers.cncf.kubernetes` to get rid of the warning.
[2025-10-28T12:33:50.723-0400] {logging_mixin.py:151} INFO - [2025-10-28T12:33:50.722-0400] {dag.py:2915} INFO - Sync 1 DAGs
[2025-10-28T12:33:50.726-0400] {logging_mixin.py:151} INFO - [2025-10-28T12:33:50.726-0400] {dag.py:3696} INFO - Setting next_dagrun for example_local_kubernetes_executor to None, run_after=None
[2025-10-28T12:33:50.733-0400] {processor.py:179} INFO - Processing /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.434 seconds
[2025-10-28T12:35:14.499-0400] {processor.py:157} INFO - Started process (PID=33713) to work on /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T12:35:14.501-0400] {processor.py:829} INFO - Processing file /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-28T12:35:14.502-0400] {logging_mixin.py:151} INFO - [2025-10-28T12:35:14.502-0400] {dagbag.py:539} INFO - Filling up the DagBag from /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T12:35:14.506-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/dataset.py:23 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:35:14.506-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/dataset.py:38 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:35:14.507-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/dataset.py:54 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:35:14.508-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/dataset.py:74 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:35:14.508-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/dag_run.py:26 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:35:14.761-0400] {processor.py:839} INFO - DAG(s) dict_keys(['example_local_kubernetes_executor']) retrieved from /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T12:35:14.768-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/taskinstance.py:27 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:35:14.799-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/serialized_objects.py:1527 DeprecationWarning: This module is deprecated. The `cncf.kubernetes` provider before version 7.4.0 uses this module - you should migrate to a newer version of `cncf.kubernetes` to get rid of this warning. If you import the module via `airflow.kubernetes` import, please use `cncf.kubernetes' provider 7.4.0+ and switch all your imports to use `apache.airflow.providers.cncf.kubernetes` to get rid of the warning.
[2025-10-28T12:35:14.815-0400] {logging_mixin.py:151} INFO - [2025-10-28T12:35:14.815-0400] {dag.py:2915} INFO - Sync 1 DAGs
[2025-10-28T12:35:14.817-0400] {logging_mixin.py:151} INFO - [2025-10-28T12:35:14.817-0400] {dag.py:3696} INFO - Setting next_dagrun for example_local_kubernetes_executor to None, run_after=None
[2025-10-28T12:35:14.823-0400] {processor.py:179} INFO - Processing /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.324 seconds
[2025-10-28T12:36:44.267-0400] {processor.py:157} INFO - Started process (PID=34532) to work on /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T12:36:44.269-0400] {processor.py:829} INFO - Processing file /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-28T12:36:44.269-0400] {logging_mixin.py:151} INFO - [2025-10-28T12:36:44.269-0400] {dagbag.py:539} INFO - Filling up the DagBag from /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T12:36:44.273-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/dataset.py:23 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:36:44.274-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/dataset.py:38 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:36:44.274-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/dataset.py:54 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:36:44.275-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/dataset.py:74 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:36:44.276-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/dag_run.py:26 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:36:44.566-0400] {processor.py:839} INFO - DAG(s) dict_keys(['example_local_kubernetes_executor']) retrieved from /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T12:36:44.575-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/taskinstance.py:27 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:36:44.611-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/serialized_objects.py:1527 DeprecationWarning: This module is deprecated. The `cncf.kubernetes` provider before version 7.4.0 uses this module - you should migrate to a newer version of `cncf.kubernetes` to get rid of this warning. If you import the module via `airflow.kubernetes` import, please use `cncf.kubernetes' provider 7.4.0+ and switch all your imports to use `apache.airflow.providers.cncf.kubernetes` to get rid of the warning.
[2025-10-28T12:36:44.633-0400] {logging_mixin.py:151} INFO - [2025-10-28T12:36:44.633-0400] {dag.py:2915} INFO - Sync 1 DAGs
[2025-10-28T12:36:44.636-0400] {logging_mixin.py:151} INFO - [2025-10-28T12:36:44.636-0400] {dag.py:3696} INFO - Setting next_dagrun for example_local_kubernetes_executor to None, run_after=None
[2025-10-28T12:36:44.643-0400] {processor.py:179} INFO - Processing /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.376 seconds
[2025-10-28T12:38:08.628-0400] {processor.py:157} INFO - Started process (PID=35309) to work on /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T12:38:08.629-0400] {processor.py:829} INFO - Processing file /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-28T12:38:08.630-0400] {logging_mixin.py:151} INFO - [2025-10-28T12:38:08.629-0400] {dagbag.py:539} INFO - Filling up the DagBag from /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T12:38:08.633-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/dataset.py:23 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:38:08.633-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/dataset.py:38 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:38:08.634-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/dataset.py:54 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:38:08.634-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/dataset.py:74 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:38:08.635-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/dag_run.py:26 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:38:08.866-0400] {processor.py:839} INFO - DAG(s) dict_keys(['example_local_kubernetes_executor']) retrieved from /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T12:38:08.873-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/taskinstance.py:27 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:38:08.899-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/serialized_objects.py:1527 DeprecationWarning: This module is deprecated. The `cncf.kubernetes` provider before version 7.4.0 uses this module - you should migrate to a newer version of `cncf.kubernetes` to get rid of this warning. If you import the module via `airflow.kubernetes` import, please use `cncf.kubernetes' provider 7.4.0+ and switch all your imports to use `apache.airflow.providers.cncf.kubernetes` to get rid of the warning.
[2025-10-28T12:38:08.913-0400] {logging_mixin.py:151} INFO - [2025-10-28T12:38:08.913-0400] {dag.py:2915} INFO - Sync 1 DAGs
[2025-10-28T12:38:08.916-0400] {logging_mixin.py:151} INFO - [2025-10-28T12:38:08.916-0400] {dag.py:3696} INFO - Setting next_dagrun for example_local_kubernetes_executor to None, run_after=None
[2025-10-28T12:38:08.922-0400] {processor.py:179} INFO - Processing /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.295 seconds
[2025-10-28T12:39:18.522-0400] {processor.py:157} INFO - Started process (PID=36307) to work on /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T12:39:18.524-0400] {processor.py:829} INFO - Processing file /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-28T12:39:18.524-0400] {logging_mixin.py:151} INFO - [2025-10-28T12:39:18.524-0400] {dagbag.py:539} INFO - Filling up the DagBag from /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T12:39:18.528-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/dataset.py:23 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:39:18.529-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/dataset.py:38 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:39:18.529-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/dataset.py:54 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:39:18.530-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/dataset.py:74 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:39:18.530-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/dag_run.py:26 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:39:18.780-0400] {processor.py:839} INFO - DAG(s) dict_keys(['example_local_kubernetes_executor']) retrieved from /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T12:39:18.787-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/taskinstance.py:27 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:39:18.817-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/serialized_objects.py:1527 DeprecationWarning: This module is deprecated. The `cncf.kubernetes` provider before version 7.4.0 uses this module - you should migrate to a newer version of `cncf.kubernetes` to get rid of this warning. If you import the module via `airflow.kubernetes` import, please use `cncf.kubernetes' provider 7.4.0+ and switch all your imports to use `apache.airflow.providers.cncf.kubernetes` to get rid of the warning.
[2025-10-28T12:39:18.833-0400] {logging_mixin.py:151} INFO - [2025-10-28T12:39:18.833-0400] {dag.py:2915} INFO - Sync 1 DAGs
[2025-10-28T12:39:18.836-0400] {logging_mixin.py:151} INFO - [2025-10-28T12:39:18.836-0400] {dag.py:3696} INFO - Setting next_dagrun for example_local_kubernetes_executor to None, run_after=None
[2025-10-28T12:39:18.842-0400] {processor.py:179} INFO - Processing /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.320 seconds
[2025-10-28T12:40:28.346-0400] {processor.py:157} INFO - Started process (PID=37010) to work on /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T12:40:28.347-0400] {processor.py:829} INFO - Processing file /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-28T12:40:28.347-0400] {logging_mixin.py:151} INFO - [2025-10-28T12:40:28.347-0400] {dagbag.py:539} INFO - Filling up the DagBag from /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T12:40:28.351-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/dataset.py:23 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:40:28.352-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/dataset.py:38 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:40:28.352-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/dataset.py:54 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:40:28.353-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/dataset.py:74 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:40:28.354-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/dag_run.py:26 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:40:28.577-0400] {processor.py:839} INFO - DAG(s) dict_keys(['example_local_kubernetes_executor']) retrieved from /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T12:40:28.584-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/taskinstance.py:27 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:40:28.613-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/serialized_objects.py:1527 DeprecationWarning: This module is deprecated. The `cncf.kubernetes` provider before version 7.4.0 uses this module - you should migrate to a newer version of `cncf.kubernetes` to get rid of this warning. If you import the module via `airflow.kubernetes` import, please use `cncf.kubernetes' provider 7.4.0+ and switch all your imports to use `apache.airflow.providers.cncf.kubernetes` to get rid of the warning.
[2025-10-28T12:40:28.627-0400] {logging_mixin.py:151} INFO - [2025-10-28T12:40:28.627-0400] {dag.py:2915} INFO - Sync 1 DAGs
[2025-10-28T12:40:28.630-0400] {logging_mixin.py:151} INFO - [2025-10-28T12:40:28.630-0400] {dag.py:3696} INFO - Setting next_dagrun for example_local_kubernetes_executor to None, run_after=None
[2025-10-28T12:40:28.635-0400] {processor.py:179} INFO - Processing /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.290 seconds
[2025-10-28T12:42:09.667-0400] {processor.py:157} INFO - Started process (PID=38319) to work on /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T12:42:09.669-0400] {processor.py:829} INFO - Processing file /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-28T12:42:09.669-0400] {logging_mixin.py:151} INFO - [2025-10-28T12:42:09.669-0400] {dagbag.py:539} INFO - Filling up the DagBag from /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T12:42:09.673-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/dataset.py:23 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:42:09.674-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/dataset.py:38 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:42:09.675-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/dataset.py:54 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:42:09.675-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/dataset.py:74 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:42:09.676-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/dag_run.py:26 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:42:09.915-0400] {processor.py:839} INFO - DAG(s) dict_keys(['example_local_kubernetes_executor']) retrieved from /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T12:42:09.922-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/taskinstance.py:27 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:42:09.950-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/serialized_objects.py:1527 DeprecationWarning: This module is deprecated. The `cncf.kubernetes` provider before version 7.4.0 uses this module - you should migrate to a newer version of `cncf.kubernetes` to get rid of this warning. If you import the module via `airflow.kubernetes` import, please use `cncf.kubernetes' provider 7.4.0+ and switch all your imports to use `apache.airflow.providers.cncf.kubernetes` to get rid of the warning.
[2025-10-28T12:42:09.966-0400] {logging_mixin.py:151} INFO - [2025-10-28T12:42:09.966-0400] {dag.py:2915} INFO - Sync 1 DAGs
[2025-10-28T12:42:09.969-0400] {logging_mixin.py:151} INFO - [2025-10-28T12:42:09.969-0400] {dag.py:3696} INFO - Setting next_dagrun for example_local_kubernetes_executor to None, run_after=None
[2025-10-28T12:42:09.974-0400] {processor.py:179} INFO - Processing /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.308 seconds
[2025-10-28T12:43:18.304-0400] {processor.py:157} INFO - Started process (PID=38960) to work on /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T12:43:18.306-0400] {processor.py:829} INFO - Processing file /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-28T12:43:18.307-0400] {logging_mixin.py:151} INFO - [2025-10-28T12:43:18.307-0400] {dagbag.py:539} INFO - Filling up the DagBag from /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T12:43:18.311-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/dataset.py:23 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:43:18.312-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/dataset.py:38 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:43:18.313-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/dataset.py:54 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:43:18.314-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/dataset.py:74 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:43:18.315-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/dag_run.py:26 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:43:18.570-0400] {processor.py:839} INFO - DAG(s) dict_keys(['example_local_kubernetes_executor']) retrieved from /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T12:43:18.577-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/taskinstance.py:27 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:43:18.606-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/serialized_objects.py:1527 DeprecationWarning: This module is deprecated. The `cncf.kubernetes` provider before version 7.4.0 uses this module - you should migrate to a newer version of `cncf.kubernetes` to get rid of this warning. If you import the module via `airflow.kubernetes` import, please use `cncf.kubernetes' provider 7.4.0+ and switch all your imports to use `apache.airflow.providers.cncf.kubernetes` to get rid of the warning.
[2025-10-28T12:43:18.622-0400] {logging_mixin.py:151} INFO - [2025-10-28T12:43:18.622-0400] {dag.py:2915} INFO - Sync 1 DAGs
[2025-10-28T12:43:18.625-0400] {logging_mixin.py:151} INFO - [2025-10-28T12:43:18.625-0400] {dag.py:3696} INFO - Setting next_dagrun for example_local_kubernetes_executor to None, run_after=None
[2025-10-28T12:43:18.631-0400] {processor.py:179} INFO - Processing /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.327 seconds
[2025-10-28T12:44:36.126-0400] {processor.py:157} INFO - Started process (PID=39681) to work on /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T12:44:36.129-0400] {processor.py:829} INFO - Processing file /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-28T12:44:36.129-0400] {logging_mixin.py:151} INFO - [2025-10-28T12:44:36.129-0400] {dagbag.py:539} INFO - Filling up the DagBag from /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T12:44:36.133-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/dataset.py:23 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:44:36.134-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/dataset.py:38 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:44:36.134-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/dataset.py:54 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:44:36.135-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/dataset.py:74 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:44:36.136-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/dag_run.py:26 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:44:36.366-0400] {processor.py:839} INFO - DAG(s) dict_keys(['example_local_kubernetes_executor']) retrieved from /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T12:44:36.373-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/taskinstance.py:27 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:44:36.401-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/serialized_objects.py:1527 DeprecationWarning: This module is deprecated. The `cncf.kubernetes` provider before version 7.4.0 uses this module - you should migrate to a newer version of `cncf.kubernetes` to get rid of this warning. If you import the module via `airflow.kubernetes` import, please use `cncf.kubernetes' provider 7.4.0+ and switch all your imports to use `apache.airflow.providers.cncf.kubernetes` to get rid of the warning.
[2025-10-28T12:44:36.419-0400] {logging_mixin.py:151} INFO - [2025-10-28T12:44:36.419-0400] {dag.py:2915} INFO - Sync 1 DAGs
[2025-10-28T12:44:36.422-0400] {logging_mixin.py:151} INFO - [2025-10-28T12:44:36.422-0400] {dag.py:3696} INFO - Setting next_dagrun for example_local_kubernetes_executor to None, run_after=None
[2025-10-28T12:44:36.429-0400] {processor.py:179} INFO - Processing /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.304 seconds
[2025-10-28T12:45:49.299-0400] {processor.py:157} INFO - Started process (PID=40383) to work on /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T12:45:49.300-0400] {processor.py:829} INFO - Processing file /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-28T12:45:49.300-0400] {logging_mixin.py:151} INFO - [2025-10-28T12:45:49.300-0400] {dagbag.py:539} INFO - Filling up the DagBag from /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T12:45:49.304-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/dataset.py:23 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:45:49.305-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/dataset.py:38 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:45:49.305-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/dataset.py:54 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:45:49.306-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/dataset.py:74 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:45:49.307-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/dag_run.py:26 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:45:49.519-0400] {processor.py:839} INFO - DAG(s) dict_keys(['example_local_kubernetes_executor']) retrieved from /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T12:45:49.526-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/taskinstance.py:27 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:45:49.553-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/serialized_objects.py:1527 DeprecationWarning: This module is deprecated. The `cncf.kubernetes` provider before version 7.4.0 uses this module - you should migrate to a newer version of `cncf.kubernetes` to get rid of this warning. If you import the module via `airflow.kubernetes` import, please use `cncf.kubernetes' provider 7.4.0+ and switch all your imports to use `apache.airflow.providers.cncf.kubernetes` to get rid of the warning.
[2025-10-28T12:45:49.568-0400] {logging_mixin.py:151} INFO - [2025-10-28T12:45:49.568-0400] {dag.py:2915} INFO - Sync 1 DAGs
[2025-10-28T12:45:49.570-0400] {logging_mixin.py:151} INFO - [2025-10-28T12:45:49.570-0400] {dag.py:3696} INFO - Setting next_dagrun for example_local_kubernetes_executor to None, run_after=None
[2025-10-28T12:45:49.576-0400] {processor.py:179} INFO - Processing /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.278 seconds
[2025-10-28T12:46:56.283-0400] {processor.py:157} INFO - Started process (PID=41052) to work on /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T12:46:56.285-0400] {processor.py:829} INFO - Processing file /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-28T12:46:56.285-0400] {logging_mixin.py:151} INFO - [2025-10-28T12:46:56.285-0400] {dagbag.py:539} INFO - Filling up the DagBag from /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T12:46:56.288-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/dataset.py:23 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:46:56.289-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/dataset.py:38 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:46:56.289-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/dataset.py:54 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:46:56.290-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/dataset.py:74 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:46:56.290-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/dag_run.py:26 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:46:56.527-0400] {processor.py:839} INFO - DAG(s) dict_keys(['example_local_kubernetes_executor']) retrieved from /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T12:46:56.535-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/pydantic/taskinstance.py:27 PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
[2025-10-28T12:46:56.566-0400] {logging_mixin.py:151} WARNING - /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/serialization/serialized_objects.py:1527 DeprecationWarning: This module is deprecated. The `cncf.kubernetes` provider before version 7.4.0 uses this module - you should migrate to a newer version of `cncf.kubernetes` to get rid of this warning. If you import the module via `airflow.kubernetes` import, please use `cncf.kubernetes' provider 7.4.0+ and switch all your imports to use `apache.airflow.providers.cncf.kubernetes` to get rid of the warning.
[2025-10-28T12:46:56.582-0400] {logging_mixin.py:151} INFO - [2025-10-28T12:46:56.582-0400] {dag.py:2915} INFO - Sync 1 DAGs
[2025-10-28T12:46:56.585-0400] {logging_mixin.py:151} INFO - [2025-10-28T12:46:56.585-0400] {dag.py:3696} INFO - Setting next_dagrun for example_local_kubernetes_executor to None, run_after=None
[2025-10-28T12:46:56.592-0400] {processor.py:179} INFO - Processing /opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.310 seconds
[2025-10-28T13:31:25.650-0400] {processor.py:186} INFO - Started process (PID=68603) to work on /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T13:31:25.651-0400] {processor.py:914} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-28T13:31:25.651-0400] {logging_mixin.py:190} INFO - [2025-10-28T13:31:25.651-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T13:31:25.663-0400] {logging_mixin.py:190} INFO - [2025-10-28T13:31:25.662-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-28T13:31:25.663-0400] {logging_mixin.py:190} INFO - [2025-10-28T13:31:25.663-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-28T13:31:25.663-0400] {processor.py:927} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T13:31:25.685-0400] {processor.py:208} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.035 seconds
[2025-10-28T13:33:04.053-0400] {processor.py:186} INFO - Started process (PID=69451) to work on /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T13:33:04.055-0400] {processor.py:914} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-28T13:33:04.055-0400] {logging_mixin.py:190} INFO - [2025-10-28T13:33:04.055-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T13:33:04.070-0400] {logging_mixin.py:190} INFO - [2025-10-28T13:33:04.070-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-28T13:33:04.071-0400] {logging_mixin.py:190} INFO - [2025-10-28T13:33:04.071-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-28T13:33:04.071-0400] {processor.py:927} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T13:33:04.095-0400] {processor.py:208} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2025-10-28T13:35:17.488-0400] {processor.py:186} INFO - Started process (PID=70580) to work on /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T13:35:17.489-0400] {processor.py:914} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-28T13:35:17.489-0400] {logging_mixin.py:190} INFO - [2025-10-28T13:35:17.489-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T13:35:17.502-0400] {logging_mixin.py:190} INFO - [2025-10-28T13:35:17.501-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-28T13:35:17.502-0400] {logging_mixin.py:190} INFO - [2025-10-28T13:35:17.502-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-28T13:35:17.502-0400] {processor.py:927} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T13:35:17.525-0400] {processor.py:208} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.038 seconds
[2025-10-28T13:37:28.102-0400] {processor.py:186} INFO - Started process (PID=71712) to work on /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T13:37:28.103-0400] {processor.py:914} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-28T13:37:28.104-0400] {logging_mixin.py:190} INFO - [2025-10-28T13:37:28.104-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T13:37:28.121-0400] {logging_mixin.py:190} INFO - [2025-10-28T13:37:28.121-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-28T13:37:28.121-0400] {logging_mixin.py:190} INFO - [2025-10-28T13:37:28.121-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-28T13:37:28.122-0400] {processor.py:927} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T13:37:28.158-0400] {processor.py:208} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.057 seconds
[2025-10-28T13:39:49.836-0400] {processor.py:186} INFO - Started process (PID=72908) to work on /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T13:39:49.839-0400] {processor.py:914} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-28T13:39:49.839-0400] {logging_mixin.py:190} INFO - [2025-10-28T13:39:49.839-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T13:39:49.852-0400] {logging_mixin.py:190} INFO - [2025-10-28T13:39:49.851-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-28T13:39:49.852-0400] {logging_mixin.py:190} INFO - [2025-10-28T13:39:49.852-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-28T13:39:49.852-0400] {processor.py:927} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T13:39:49.875-0400] {processor.py:208} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.039 seconds
[2025-10-28T13:42:14.799-0400] {processor.py:186} INFO - Started process (PID=74152) to work on /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T13:42:14.801-0400] {processor.py:914} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-28T13:42:14.801-0400] {logging_mixin.py:190} INFO - [2025-10-28T13:42:14.801-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T13:42:14.814-0400] {logging_mixin.py:190} INFO - [2025-10-28T13:42:14.814-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-28T13:42:14.814-0400] {logging_mixin.py:190} INFO - [2025-10-28T13:42:14.814-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-28T13:42:14.814-0400] {processor.py:927} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T13:42:14.837-0400] {processor.py:208} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.038 seconds
[2025-10-28T13:44:37.516-0400] {processor.py:186} INFO - Started process (PID=75406) to work on /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T13:44:37.518-0400] {processor.py:914} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-28T13:44:37.519-0400] {logging_mixin.py:190} INFO - [2025-10-28T13:44:37.519-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T13:44:37.532-0400] {logging_mixin.py:190} INFO - [2025-10-28T13:44:37.532-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-28T13:44:37.532-0400] {logging_mixin.py:190} INFO - [2025-10-28T13:44:37.532-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-28T13:44:37.532-0400] {processor.py:927} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T13:44:37.555-0400] {processor.py:208} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.039 seconds
[2025-10-28T13:47:03.889-0400] {processor.py:186} INFO - Started process (PID=76690) to work on /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T13:47:03.890-0400] {processor.py:914} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-28T13:47:03.890-0400] {logging_mixin.py:190} INFO - [2025-10-28T13:47:03.890-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T13:47:03.905-0400] {logging_mixin.py:190} INFO - [2025-10-28T13:47:03.905-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-28T13:47:03.905-0400] {logging_mixin.py:190} INFO - [2025-10-28T13:47:03.905-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-28T13:47:03.905-0400] {processor.py:927} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T13:47:03.929-0400] {processor.py:208} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.041 seconds
[2025-10-28T13:49:13.046-0400] {processor.py:186} INFO - Started process (PID=77816) to work on /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T13:49:13.048-0400] {processor.py:914} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-28T13:49:13.048-0400] {logging_mixin.py:190} INFO - [2025-10-28T13:49:13.048-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T13:49:13.060-0400] {logging_mixin.py:190} INFO - [2025-10-28T13:49:13.060-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-28T13:49:13.060-0400] {logging_mixin.py:190} INFO - [2025-10-28T13:49:13.060-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-28T13:49:13.060-0400] {processor.py:927} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T13:49:13.082-0400] {processor.py:208} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.037 seconds
[2025-10-28T13:51:33.523-0400] {processor.py:186} INFO - Started process (PID=79021) to work on /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T13:51:33.524-0400] {processor.py:914} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-28T13:51:33.525-0400] {logging_mixin.py:190} INFO - [2025-10-28T13:51:33.525-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T13:51:33.546-0400] {logging_mixin.py:190} INFO - [2025-10-28T13:51:33.546-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-28T13:51:33.546-0400] {logging_mixin.py:190} INFO - [2025-10-28T13:51:33.546-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-28T13:51:33.546-0400] {processor.py:927} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T13:51:33.574-0400] {processor.py:208} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.054 seconds
[2025-10-28T13:54:04.442-0400] {processor.py:186} INFO - Started process (PID=80622) to work on /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T13:54:04.443-0400] {processor.py:914} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-28T13:54:04.443-0400] {logging_mixin.py:190} INFO - [2025-10-28T13:54:04.443-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T13:54:04.456-0400] {logging_mixin.py:190} INFO - [2025-10-28T13:54:04.455-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-28T13:54:04.456-0400] {logging_mixin.py:190} INFO - [2025-10-28T13:54:04.456-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-28T13:54:04.456-0400] {processor.py:927} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T13:54:04.478-0400] {processor.py:208} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.038 seconds
[2025-10-28T13:55:55.483-0400] {processor.py:186} INFO - Started process (PID=81584) to work on /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T13:55:55.484-0400] {processor.py:914} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-28T13:55:55.484-0400] {logging_mixin.py:190} INFO - [2025-10-28T13:55:55.484-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T13:55:55.498-0400] {logging_mixin.py:190} INFO - [2025-10-28T13:55:55.498-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-28T13:55:55.499-0400] {logging_mixin.py:190} INFO - [2025-10-28T13:55:55.498-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-28T13:55:55.499-0400] {processor.py:927} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T13:55:55.523-0400] {processor.py:208} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.041 seconds
[2025-10-28T13:58:33.348-0400] {processor.py:186} INFO - Started process (PID=82970) to work on /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T13:58:33.349-0400] {processor.py:914} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-28T13:58:33.349-0400] {logging_mixin.py:190} INFO - [2025-10-28T13:58:33.349-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T13:58:33.361-0400] {logging_mixin.py:190} INFO - [2025-10-28T13:58:33.361-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-28T13:58:33.361-0400] {logging_mixin.py:190} INFO - [2025-10-28T13:58:33.361-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-28T13:58:33.361-0400] {processor.py:927} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T13:58:33.384-0400] {processor.py:208} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.037 seconds
[2025-10-28T14:00:36.591-0400] {processor.py:186} INFO - Started process (PID=84327) to work on /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T14:00:36.592-0400] {processor.py:914} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-28T14:00:36.593-0400] {logging_mixin.py:190} INFO - [2025-10-28T14:00:36.593-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T14:00:36.605-0400] {logging_mixin.py:190} INFO - [2025-10-28T14:00:36.605-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-28T14:00:36.605-0400] {logging_mixin.py:190} INFO - [2025-10-28T14:00:36.605-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-28T14:00:36.605-0400] {processor.py:927} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T14:00:36.629-0400] {processor.py:208} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.040 seconds
[2025-10-28T14:04:02.003-0400] {processor.py:186} INFO - Started process (PID=86783) to work on /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T14:04:02.005-0400] {processor.py:914} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-28T14:04:02.005-0400] {logging_mixin.py:190} INFO - [2025-10-28T14:04:02.005-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T14:04:02.020-0400] {logging_mixin.py:190} INFO - [2025-10-28T14:04:02.020-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-28T14:04:02.020-0400] {logging_mixin.py:190} INFO - [2025-10-28T14:04:02.020-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-28T14:04:02.020-0400] {processor.py:927} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T14:04:02.045-0400] {processor.py:208} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2025-10-28T14:06:23.963-0400] {processor.py:186} INFO - Started process (PID=88348) to work on /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T14:06:23.965-0400] {processor.py:914} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-28T14:06:23.966-0400] {logging_mixin.py:190} INFO - [2025-10-28T14:06:23.966-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T14:06:23.984-0400] {logging_mixin.py:190} INFO - [2025-10-28T14:06:23.983-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-28T14:06:23.984-0400] {logging_mixin.py:190} INFO - [2025-10-28T14:06:23.984-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-28T14:06:23.984-0400] {processor.py:927} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T14:06:24.009-0400] {processor.py:208} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.047 seconds
[2025-10-28T14:09:55.057-0400] {processor.py:186} INFO - Started process (PID=90710) to work on /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T14:09:55.060-0400] {processor.py:914} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-28T14:09:55.060-0400] {logging_mixin.py:190} INFO - [2025-10-28T14:09:55.060-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T14:09:55.072-0400] {logging_mixin.py:190} INFO - [2025-10-28T14:09:55.072-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-28T14:09:55.072-0400] {logging_mixin.py:190} INFO - [2025-10-28T14:09:55.072-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-28T14:09:55.072-0400] {processor.py:927} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T14:09:55.095-0400] {processor.py:208} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.038 seconds
[2025-10-28T14:12:11.473-0400] {processor.py:186} INFO - Started process (PID=92120) to work on /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T14:12:11.474-0400] {processor.py:914} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-28T14:12:11.475-0400] {logging_mixin.py:190} INFO - [2025-10-28T14:12:11.475-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T14:12:11.492-0400] {logging_mixin.py:190} INFO - [2025-10-28T14:12:11.491-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-28T14:12:11.492-0400] {logging_mixin.py:190} INFO - [2025-10-28T14:12:11.492-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-28T14:12:11.492-0400] {processor.py:927} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T14:12:11.518-0400] {processor.py:208} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.046 seconds
[2025-10-28T14:13:51.228-0400] {processor.py:186} INFO - Started process (PID=93004) to work on /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T14:13:51.229-0400] {processor.py:914} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-28T14:13:51.230-0400] {logging_mixin.py:190} INFO - [2025-10-28T14:13:51.230-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T14:13:51.244-0400] {logging_mixin.py:190} INFO - [2025-10-28T14:13:51.243-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-28T14:13:51.244-0400] {logging_mixin.py:190} INFO - [2025-10-28T14:13:51.244-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-28T14:13:51.244-0400] {processor.py:927} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T14:13:51.268-0400] {processor.py:208} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.041 seconds
[2025-10-28T14:18:04.680-0400] {processor.py:186} INFO - Started process (PID=95697) to work on /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T14:18:04.681-0400] {processor.py:914} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-28T14:18:04.682-0400] {logging_mixin.py:190} INFO - [2025-10-28T14:18:04.682-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T14:18:04.701-0400] {logging_mixin.py:190} INFO - [2025-10-28T14:18:04.701-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-28T14:18:04.701-0400] {logging_mixin.py:190} INFO - [2025-10-28T14:18:04.701-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-28T14:18:04.701-0400] {processor.py:927} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T14:18:04.730-0400] {processor.py:208} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.052 seconds
[2025-10-28T14:19:49.033-0400] {processor.py:186} INFO - Started process (PID=96668) to work on /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T14:19:49.034-0400] {processor.py:914} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-28T14:19:49.035-0400] {logging_mixin.py:190} INFO - [2025-10-28T14:19:49.035-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T14:19:49.050-0400] {logging_mixin.py:190} INFO - [2025-10-28T14:19:49.049-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-28T14:19:49.050-0400] {logging_mixin.py:190} INFO - [2025-10-28T14:19:49.050-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-28T14:19:49.050-0400] {processor.py:927} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T14:19:49.080-0400] {processor.py:208} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.048 seconds
[2025-10-28T14:22:17.088-0400] {processor.py:186} INFO - Started process (PID=98081) to work on /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T14:22:17.089-0400] {processor.py:914} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-28T14:22:17.089-0400] {logging_mixin.py:190} INFO - [2025-10-28T14:22:17.089-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T14:22:17.101-0400] {logging_mixin.py:190} INFO - [2025-10-28T14:22:17.101-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-28T14:22:17.101-0400] {logging_mixin.py:190} INFO - [2025-10-28T14:22:17.101-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-28T14:22:17.101-0400] {processor.py:927} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T14:22:17.124-0400] {processor.py:208} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.037 seconds
[2025-10-28T14:24:45.908-0400] {processor.py:186} INFO - Started process (PID=99380) to work on /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T14:24:45.910-0400] {processor.py:914} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-28T14:24:45.910-0400] {logging_mixin.py:190} INFO - [2025-10-28T14:24:45.910-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T14:24:45.923-0400] {logging_mixin.py:190} INFO - [2025-10-28T14:24:45.923-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-28T14:24:45.923-0400] {logging_mixin.py:190} INFO - [2025-10-28T14:24:45.923-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-28T14:24:45.923-0400] {processor.py:927} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T14:24:45.945-0400] {processor.py:208} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.038 seconds
[2025-10-28T14:27:07.814-0400] {processor.py:186} INFO - Started process (PID=846) to work on /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T14:27:07.816-0400] {processor.py:914} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-28T14:27:07.818-0400] {logging_mixin.py:190} INFO - [2025-10-28T14:27:07.817-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T14:27:07.846-0400] {logging_mixin.py:190} INFO - [2025-10-28T14:27:07.846-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-28T14:27:07.846-0400] {logging_mixin.py:190} INFO - [2025-10-28T14:27:07.846-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-28T14:27:07.846-0400] {processor.py:927} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T14:27:07.891-0400] {processor.py:208} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.078 seconds
[2025-10-28T14:29:37.553-0400] {processor.py:186} INFO - Started process (PID=2205) to work on /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T14:29:37.556-0400] {processor.py:914} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-28T14:29:37.556-0400] {logging_mixin.py:190} INFO - [2025-10-28T14:29:37.556-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T14:29:37.567-0400] {logging_mixin.py:190} INFO - [2025-10-28T14:29:37.567-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-28T14:29:37.568-0400] {logging_mixin.py:190} INFO - [2025-10-28T14:29:37.567-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-28T14:29:37.568-0400] {processor.py:927} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T14:29:37.589-0400] {processor.py:208} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.037 seconds
[2025-10-28T14:31:47.186-0400] {processor.py:186} INFO - Started process (PID=3277) to work on /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T14:31:47.187-0400] {processor.py:914} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-28T14:31:47.187-0400] {logging_mixin.py:190} INFO - [2025-10-28T14:31:47.187-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T14:31:47.201-0400] {logging_mixin.py:190} INFO - [2025-10-28T14:31:47.201-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-28T14:31:47.202-0400] {logging_mixin.py:190} INFO - [2025-10-28T14:31:47.202-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-28T14:31:47.202-0400] {processor.py:927} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T14:31:47.226-0400] {processor.py:208} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.041 seconds
[2025-10-28T14:34:03.181-0400] {processor.py:186} INFO - Started process (PID=4380) to work on /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T14:34:03.182-0400] {processor.py:914} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-28T14:34:03.182-0400] {logging_mixin.py:190} INFO - [2025-10-28T14:34:03.182-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T14:34:03.194-0400] {logging_mixin.py:190} INFO - [2025-10-28T14:34:03.194-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-28T14:34:03.194-0400] {logging_mixin.py:190} INFO - [2025-10-28T14:34:03.194-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-28T14:34:03.194-0400] {processor.py:927} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T14:34:03.215-0400] {processor.py:208} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.036 seconds
[2025-10-28T14:36:14.886-0400] {processor.py:186} INFO - Started process (PID=5511) to work on /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T14:36:14.887-0400] {processor.py:914} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-28T14:36:14.887-0400] {logging_mixin.py:190} INFO - [2025-10-28T14:36:14.887-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T14:36:14.900-0400] {logging_mixin.py:190} INFO - [2025-10-28T14:36:14.900-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-28T14:36:14.900-0400] {logging_mixin.py:190} INFO - [2025-10-28T14:36:14.900-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-28T14:36:14.900-0400] {processor.py:927} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T14:36:14.923-0400] {processor.py:208} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.037 seconds
[2025-10-28T14:38:26.769-0400] {processor.py:186} INFO - Started process (PID=6651) to work on /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T14:38:26.771-0400] {processor.py:914} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-28T14:38:26.771-0400] {logging_mixin.py:190} INFO - [2025-10-28T14:38:26.771-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T14:38:26.783-0400] {logging_mixin.py:190} INFO - [2025-10-28T14:38:26.783-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-28T14:38:26.784-0400] {logging_mixin.py:190} INFO - [2025-10-28T14:38:26.784-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-28T14:38:26.784-0400] {processor.py:927} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T14:38:26.806-0400] {processor.py:208} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.037 seconds
[2025-10-28T14:40:39.246-0400] {processor.py:186} INFO - Started process (PID=7806) to work on /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T14:40:39.247-0400] {processor.py:914} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-28T14:40:39.247-0400] {logging_mixin.py:190} INFO - [2025-10-28T14:40:39.247-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T14:40:39.261-0400] {logging_mixin.py:190} INFO - [2025-10-28T14:40:39.261-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-28T14:40:39.261-0400] {logging_mixin.py:190} INFO - [2025-10-28T14:40:39.261-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-28T14:40:39.261-0400] {processor.py:927} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T14:40:39.285-0400] {processor.py:208} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.040 seconds
[2025-10-28T14:42:17.363-0400] {processor.py:186} INFO - Started process (PID=8889) to work on /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T14:42:17.364-0400] {processor.py:914} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-28T14:42:17.364-0400] {logging_mixin.py:190} INFO - [2025-10-28T14:42:17.364-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T14:42:17.381-0400] {logging_mixin.py:190} INFO - [2025-10-28T14:42:17.381-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-28T14:42:17.381-0400] {logging_mixin.py:190} INFO - [2025-10-28T14:42:17.381-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-28T14:42:17.381-0400] {processor.py:927} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T14:42:17.403-0400] {processor.py:208} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.041 seconds
[2025-10-28T14:44:01.990-0400] {processor.py:186} INFO - Started process (PID=9837) to work on /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T14:44:01.991-0400] {processor.py:914} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-28T14:44:01.991-0400] {logging_mixin.py:190} INFO - [2025-10-28T14:44:01.991-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T14:44:02.002-0400] {logging_mixin.py:190} INFO - [2025-10-28T14:44:02.002-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-28T14:44:02.003-0400] {logging_mixin.py:190} INFO - [2025-10-28T14:44:02.002-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-28T14:44:02.003-0400] {processor.py:927} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T14:44:02.025-0400] {processor.py:208} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.036 seconds
[2025-10-28T14:46:19.038-0400] {processor.py:186} INFO - Started process (PID=10989) to work on /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T14:46:19.039-0400] {processor.py:914} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-28T14:46:19.039-0400] {logging_mixin.py:190} INFO - [2025-10-28T14:46:19.039-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T14:46:19.050-0400] {logging_mixin.py:190} INFO - [2025-10-28T14:46:19.050-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-28T14:46:19.050-0400] {logging_mixin.py:190} INFO - [2025-10-28T14:46:19.050-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-28T14:46:19.050-0400] {processor.py:927} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T14:46:19.072-0400] {processor.py:208} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.035 seconds
[2025-10-28T14:49:03.358-0400] {processor.py:186} INFO - Started process (PID=12662) to work on /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T14:49:03.360-0400] {processor.py:914} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-28T14:49:03.360-0400] {logging_mixin.py:190} INFO - [2025-10-28T14:49:03.360-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T14:49:03.371-0400] {logging_mixin.py:190} INFO - [2025-10-28T14:49:03.371-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-28T14:49:03.372-0400] {logging_mixin.py:190} INFO - [2025-10-28T14:49:03.372-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-28T14:49:03.372-0400] {processor.py:927} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T14:49:03.394-0400] {processor.py:208} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.037 seconds
[2025-10-28T14:50:42.242-0400] {processor.py:186} INFO - Started process (PID=13504) to work on /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T14:50:42.243-0400] {processor.py:914} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-28T14:50:42.244-0400] {logging_mixin.py:190} INFO - [2025-10-28T14:50:42.243-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T14:50:42.255-0400] {logging_mixin.py:190} INFO - [2025-10-28T14:50:42.255-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-28T14:50:42.256-0400] {logging_mixin.py:190} INFO - [2025-10-28T14:50:42.256-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-28T14:50:42.256-0400] {processor.py:927} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T14:50:42.278-0400] {processor.py:208} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.036 seconds
[2025-10-28T14:54:02.026-0400] {processor.py:186} INFO - Started process (PID=15476) to work on /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T14:54:02.027-0400] {processor.py:914} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-28T14:54:02.027-0400] {logging_mixin.py:190} INFO - [2025-10-28T14:54:02.027-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T14:54:02.039-0400] {logging_mixin.py:190} INFO - [2025-10-28T14:54:02.039-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-28T14:54:02.040-0400] {logging_mixin.py:190} INFO - [2025-10-28T14:54:02.039-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-28T14:54:02.040-0400] {processor.py:927} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T14:54:02.062-0400] {processor.py:208} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.036 seconds
[2025-10-28T14:55:37.658-0400] {processor.py:186} INFO - Started process (PID=16043) to work on /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T14:55:37.658-0400] {processor.py:914} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-28T14:55:37.659-0400] {logging_mixin.py:190} INFO - [2025-10-28T14:55:37.659-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T14:55:37.672-0400] {logging_mixin.py:190} INFO - [2025-10-28T14:55:37.671-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-28T14:55:37.672-0400] {logging_mixin.py:190} INFO - [2025-10-28T14:55:37.672-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-28T14:55:37.672-0400] {processor.py:927} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T14:55:37.694-0400] {processor.py:208} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.037 seconds
[2025-10-28T14:57:47.822-0400] {processor.py:186} INFO - Started process (PID=16808) to work on /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T14:57:47.823-0400] {processor.py:914} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-28T14:57:47.824-0400] {logging_mixin.py:190} INFO - [2025-10-28T14:57:47.823-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T14:57:47.836-0400] {logging_mixin.py:190} INFO - [2025-10-28T14:57:47.836-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-28T14:57:47.836-0400] {logging_mixin.py:190} INFO - [2025-10-28T14:57:47.836-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-28T14:57:47.836-0400] {processor.py:927} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T14:57:47.859-0400] {processor.py:208} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.038 seconds
[2025-10-28T14:59:22.934-0400] {processor.py:186} INFO - Started process (PID=17765) to work on /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T14:59:22.936-0400] {processor.py:914} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-28T14:59:22.936-0400] {logging_mixin.py:190} INFO - [2025-10-28T14:59:22.936-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T14:59:22.951-0400] {logging_mixin.py:190} INFO - [2025-10-28T14:59:22.951-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-28T14:59:22.951-0400] {logging_mixin.py:190} INFO - [2025-10-28T14:59:22.951-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-28T14:59:22.951-0400] {processor.py:927} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T14:59:22.976-0400] {processor.py:208} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.044 seconds
[2025-10-28T15:00:55.359-0400] {processor.py:186} INFO - Started process (PID=18267) to work on /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T15:00:55.360-0400] {processor.py:914} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-28T15:00:55.361-0400] {logging_mixin.py:190} INFO - [2025-10-28T15:00:55.360-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T15:00:55.372-0400] {logging_mixin.py:190} INFO - [2025-10-28T15:00:55.372-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-28T15:00:55.372-0400] {logging_mixin.py:190} INFO - [2025-10-28T15:00:55.372-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-28T15:00:55.372-0400] {processor.py:927} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T15:00:55.394-0400] {processor.py:208} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.036 seconds
[2025-10-28T15:03:01.485-0400] {processor.py:186} INFO - Started process (PID=18932) to work on /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T15:03:01.486-0400] {processor.py:914} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-28T15:03:01.486-0400] {logging_mixin.py:190} INFO - [2025-10-28T15:03:01.486-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T15:03:01.498-0400] {logging_mixin.py:190} INFO - [2025-10-28T15:03:01.498-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-28T15:03:01.498-0400] {logging_mixin.py:190} INFO - [2025-10-28T15:03:01.498-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-28T15:03:01.498-0400] {processor.py:927} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T15:03:01.521-0400] {processor.py:208} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.037 seconds
[2025-10-28T15:05:04.750-0400] {processor.py:186} INFO - Started process (PID=19910) to work on /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T15:05:04.752-0400] {processor.py:914} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-28T15:05:04.752-0400] {logging_mixin.py:190} INFO - [2025-10-28T15:05:04.752-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T15:05:04.763-0400] {logging_mixin.py:190} INFO - [2025-10-28T15:05:04.763-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-28T15:05:04.764-0400] {logging_mixin.py:190} INFO - [2025-10-28T15:05:04.763-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-28T15:05:04.764-0400] {processor.py:927} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T15:05:04.786-0400] {processor.py:208} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.037 seconds
[2025-10-28T15:06:36.133-0400] {processor.py:186} INFO - Started process (PID=20401) to work on /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T15:06:36.134-0400] {processor.py:914} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-28T15:06:36.134-0400] {logging_mixin.py:190} INFO - [2025-10-28T15:06:36.134-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T15:06:36.147-0400] {logging_mixin.py:190} INFO - [2025-10-28T15:06:36.147-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-28T15:06:36.147-0400] {logging_mixin.py:190} INFO - [2025-10-28T15:06:36.147-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-28T15:06:36.147-0400] {processor.py:927} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T15:06:36.170-0400] {processor.py:208} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.037 seconds
[2025-10-28T15:08:49.787-0400] {processor.py:186} INFO - Started process (PID=21091) to work on /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T15:08:49.788-0400] {processor.py:914} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-28T15:08:49.788-0400] {logging_mixin.py:190} INFO - [2025-10-28T15:08:49.788-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T15:08:49.802-0400] {logging_mixin.py:190} INFO - [2025-10-28T15:08:49.802-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-28T15:08:49.802-0400] {logging_mixin.py:190} INFO - [2025-10-28T15:08:49.802-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-28T15:08:49.802-0400] {processor.py:927} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T15:08:49.825-0400] {processor.py:208} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.039 seconds
[2025-10-28T15:57:15.319-0400] {processor.py:186} INFO - Started process (PID=21934) to work on /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T15:57:15.320-0400] {processor.py:914} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-28T15:57:15.320-0400] {logging_mixin.py:190} INFO - [2025-10-28T15:57:15.320-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T15:57:15.331-0400] {logging_mixin.py:190} INFO - [2025-10-28T15:57:15.331-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-28T15:57:15.331-0400] {logging_mixin.py:190} INFO - [2025-10-28T15:57:15.331-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-28T15:57:15.331-0400] {processor.py:927} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T15:57:15.354-0400] {processor.py:208} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.036 seconds
[2025-10-28T15:59:23.087-0400] {processor.py:186} INFO - Started process (PID=22621) to work on /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T15:59:23.088-0400] {processor.py:914} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-28T15:59:23.089-0400] {logging_mixin.py:190} INFO - [2025-10-28T15:59:23.089-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T15:59:23.102-0400] {logging_mixin.py:190} INFO - [2025-10-28T15:59:23.101-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-28T15:59:23.102-0400] {logging_mixin.py:190} INFO - [2025-10-28T15:59:23.102-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-28T15:59:23.102-0400] {processor.py:927} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T15:59:23.125-0400] {processor.py:208} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.039 seconds
[2025-10-28T16:01:38.933-0400] {processor.py:186} INFO - Started process (PID=23573) to work on /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T16:01:38.935-0400] {processor.py:914} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-28T16:01:38.935-0400] {logging_mixin.py:190} INFO - [2025-10-28T16:01:38.935-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T16:01:38.948-0400] {logging_mixin.py:190} INFO - [2025-10-28T16:01:38.948-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-28T16:01:38.948-0400] {logging_mixin.py:190} INFO - [2025-10-28T16:01:38.948-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-28T16:01:38.948-0400] {processor.py:927} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T16:01:38.970-0400] {processor.py:208} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.038 seconds
[2025-10-28T16:03:17.093-0400] {processor.py:186} INFO - Started process (PID=24093) to work on /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T16:03:17.095-0400] {processor.py:914} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-28T16:03:17.095-0400] {logging_mixin.py:190} INFO - [2025-10-28T16:03:17.095-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T16:03:17.107-0400] {logging_mixin.py:190} INFO - [2025-10-28T16:03:17.106-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-28T16:03:17.107-0400] {logging_mixin.py:190} INFO - [2025-10-28T16:03:17.107-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-28T16:03:17.107-0400] {processor.py:927} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T16:03:17.128-0400] {processor.py:208} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.036 seconds
[2025-10-28T16:05:38.733-0400] {processor.py:186} INFO - Started process (PID=24806) to work on /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T16:05:38.735-0400] {processor.py:914} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-28T16:05:38.735-0400] {logging_mixin.py:190} INFO - [2025-10-28T16:05:38.735-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T16:05:38.747-0400] {logging_mixin.py:190} INFO - [2025-10-28T16:05:38.747-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-28T16:05:38.747-0400] {logging_mixin.py:190} INFO - [2025-10-28T16:05:38.747-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-28T16:05:38.747-0400] {processor.py:927} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T16:05:38.769-0400] {processor.py:208} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.037 seconds
[2025-10-28T16:08:37.641-0400] {processor.py:186} INFO - Started process (PID=26340) to work on /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T16:08:37.642-0400] {processor.py:914} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-28T16:08:37.642-0400] {logging_mixin.py:190} INFO - [2025-10-28T16:08:37.642-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T16:08:37.654-0400] {logging_mixin.py:190} INFO - [2025-10-28T16:08:37.654-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-28T16:08:37.654-0400] {logging_mixin.py:190} INFO - [2025-10-28T16:08:37.654-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-28T16:08:37.654-0400] {processor.py:927} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T16:08:37.676-0400] {processor.py:208} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.036 seconds
[2025-10-28T16:10:17.823-0400] {processor.py:186} INFO - Started process (PID=26860) to work on /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T16:10:17.824-0400] {processor.py:914} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-28T16:10:17.825-0400] {logging_mixin.py:190} INFO - [2025-10-28T16:10:17.825-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T16:10:17.837-0400] {logging_mixin.py:190} INFO - [2025-10-28T16:10:17.837-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-28T16:10:17.837-0400] {logging_mixin.py:190} INFO - [2025-10-28T16:10:17.837-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-28T16:10:17.837-0400] {processor.py:927} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T16:10:17.861-0400] {processor.py:208} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.039 seconds
[2025-10-28T16:13:02.357-0400] {processor.py:186} INFO - Started process (PID=27942) to work on /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T16:13:02.358-0400] {processor.py:914} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-28T16:13:02.359-0400] {logging_mixin.py:190} INFO - [2025-10-28T16:13:02.359-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T16:13:02.371-0400] {logging_mixin.py:190} INFO - [2025-10-28T16:13:02.371-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-28T16:13:02.371-0400] {logging_mixin.py:190} INFO - [2025-10-28T16:13:02.371-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-28T16:13:02.371-0400] {processor.py:927} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T16:13:02.394-0400] {processor.py:208} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.038 seconds
[2025-10-28T16:14:57.776-0400] {processor.py:186} INFO - Started process (PID=28764) to work on /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T16:14:57.778-0400] {processor.py:914} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-28T16:14:57.779-0400] {logging_mixin.py:190} INFO - [2025-10-28T16:14:57.779-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T16:14:57.798-0400] {logging_mixin.py:190} INFO - [2025-10-28T16:14:57.798-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-28T16:14:57.798-0400] {logging_mixin.py:190} INFO - [2025-10-28T16:14:57.798-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-28T16:14:57.798-0400] {processor.py:927} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T16:14:57.827-0400] {processor.py:208} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.052 seconds
[2025-10-28T16:17:45.601-0400] {processor.py:186} INFO - Started process (PID=29908) to work on /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T16:17:45.603-0400] {processor.py:914} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-28T16:17:45.603-0400] {logging_mixin.py:190} INFO - [2025-10-28T16:17:45.603-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T16:17:45.615-0400] {logging_mixin.py:190} INFO - [2025-10-28T16:17:45.615-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-28T16:17:45.615-0400] {logging_mixin.py:190} INFO - [2025-10-28T16:17:45.615-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-28T16:17:45.615-0400] {processor.py:927} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T16:17:45.638-0400] {processor.py:208} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.037 seconds
[2025-10-28T16:19:21.046-0400] {processor.py:186} INFO - Started process (PID=30394) to work on /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T16:19:21.048-0400] {processor.py:914} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-28T16:19:21.048-0400] {logging_mixin.py:190} INFO - [2025-10-28T16:19:21.048-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T16:19:21.062-0400] {logging_mixin.py:190} INFO - [2025-10-28T16:19:21.062-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-28T16:19:21.062-0400] {logging_mixin.py:190} INFO - [2025-10-28T16:19:21.062-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-28T16:19:21.063-0400] {processor.py:927} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-28T16:19:21.087-0400] {processor.py:208} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.041 seconds
