[2025-10-31T03:06:03.588+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline_dag.transcribe_youtube manual__2025-10-31T03:05:57.604984+00:00 [queued]>
[2025-10-31T03:06:03.591+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline_dag.transcribe_youtube manual__2025-10-31T03:05:57.604984+00:00 [queued]>
[2025-10-31T03:06:03.591+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-10-31T03:06:03.597+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): transcribe_youtube> on 2025-10-31 03:05:57.604984+00:00
[2025-10-31T03:06:03.600+0000] {standard_task_runner.py:57} INFO - Started process 50 to run task
[2025-10-31T03:06:03.602+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'data_pipeline_dag', 'transcribe_youtube', 'manual__2025-10-31T03:05:57.604984+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline_dag.py', '--cfg-path', '/tmp/tmprxq_r065']
[2025-10-31T03:06:03.603+0000] {standard_task_runner.py:85} INFO - Job 6: Subtask transcribe_youtube
[2025-10-31T03:06:03.617+0000] {task_command.py:416} INFO - Running <TaskInstance: data_pipeline_dag.transcribe_youtube manual__2025-10-31T03:05:57.604984+00:00 [running]> on host d58ba3f3b0d0
[2025-10-31T03:06:03.637+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='data_pipeline_dag' AIRFLOW_CTX_TASK_ID='transcribe_youtube' AIRFLOW_CTX_EXECUTION_DATE='2025-10-31T03:05:57.604984+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-31T03:05:57.604984+00:00'
[2025-10-31T03:06:03.638+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-31T03:06:03.638+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/airflow/dags/scripts/transcription.py']
[2025-10-31T03:06:03.641+0000] {subprocess.py:86} INFO - Output:
[2025-10-31T03:06:03.696+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-10-31T03:06:03.698+0000] {subprocess.py:93} INFO -   File "/opt/airflow/dags/scripts/transcription.py", line 3, in <module>
[2025-10-31T03:06:03.698+0000] {subprocess.py:93} INFO -     import yt_dlp
[2025-10-31T03:06:03.698+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'yt_dlp'
[2025-10-31T03:06:03.698+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-10-31T03:06:03.701+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-10-31T03:06:03.702+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=data_pipeline_dag, task_id=transcribe_youtube, execution_date=20251031T030557, start_date=20251031T030603, end_date=20251031T030603
[2025-10-31T03:06:03.711+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 6 for task transcribe_youtube (Bash command failed. The command returned a non-zero exit code 1.; 50)
[2025-10-31T03:06:03.744+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-10-31T03:06:03.751+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
