[2025-10-27T17:18:45.842-0400] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: onboarding_data_pipeline.validation_tasks.detect_anomalies manual__2025-10-27T21:18:32.053379+00:00 [queued]>
[2025-10-27T17:18:45.844-0400] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: onboarding_data_pipeline.validation_tasks.detect_anomalies manual__2025-10-27T21:18:32.053379+00:00 [queued]>
[2025-10-27T17:18:45.844-0400] {taskinstance.py:1359} INFO - Starting attempt 1 of 3
[2025-10-27T17:18:45.847-0400] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): validation_tasks.detect_anomalies> on 2025-10-27 21:18:32.053379+00:00
[2025-10-27T17:18:45.851-0400] {standard_task_runner.py:57} INFO - Started process 64477 to run task
[2025-10-27T17:18:45.854-0400] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'onboarding_data_pipeline', 'validation_tasks.detect_anomalies', 'manual__2025-10-27T21:18:32.053379+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/main_pipeline_dag.py', '--cfg-path', '/var/folders/bq/zp7dztbn5yxb9ljzbt_99_dr0000gn/T/tmphi__x988']
[2025-10-27T17:18:45.855-0400] {standard_task_runner.py:85} INFO - Job 9: Subtask validation_tasks.detect_anomalies
[2025-10-27T17:18:45.872-0400] {task_command.py:415} INFO - Running <TaskInstance: onboarding_data_pipeline.validation_tasks.detect_anomalies manual__2025-10-27T21:18:32.053379+00:00 [running]> on host mithuns-macbook-pro.local
[2025-10-27T17:18:45.886-0400] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='team13@example.com' AIRFLOW_CTX_DAG_OWNER='Team13' AIRFLOW_CTX_DAG_ID='onboarding_data_pipeline' AIRFLOW_CTX_TASK_ID='validation_tasks.detect_anomalies' AIRFLOW_CTX_EXECUTION_DATE='2025-10-27T21:18:32.053379+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-27T21:18:32.053379+00:00'
[2025-10-27T17:18:45.887-0400] {logging_mixin.py:151} INFO - Detecting data anomalies...
[2025-10-27T17:18:45.888-0400] {logging_mixin.py:151} INFO - Found 0 anomalies
[2025-10-27T17:18:45.888-0400] {python.py:194} INFO - Done. Returned value was: anomalies_0
[2025-10-27T17:18:45.891-0400] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=onboarding_data_pipeline, task_id=validation_tasks.detect_anomalies, execution_date=20251027T211832, start_date=20251027T211845, end_date=20251027T211845
[2025-10-27T17:18:45.907-0400] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-10-27T17:18:45.915-0400] {taskinstance.py:2776} INFO - 1 downstream tasks scheduled from follow-on schedule check
